### ISSUE TITLE
Addition of more tools for better optimization

### ISSUE THREAD

**Issue by oriolbcn** [albertbellonch/piet#15]
I have created a new version of piet including more tools since we needed it for Camaloon. I have also organized the code a little bit different. Check it out and let me know if you want to merge it. Here it is: https://github.com/oriolbcn/piet

**It is not backwards compatible with the current version**

**Comment by albertbellonch** [comment]
Hi all,

I'd love to add more tools to `piet`, but I'd like to keep it backwards-compatible. It is a small piece of software, so I understand it should not be extremely difficult to achieve.

@brodock, if you want to issue a PR with this new options (and the convenient tests for it), I will love to merge it, of course :D 

Best,
