### ISSUE TITLE
Is there an option to keep the original image file?

### ISSUE THREAD

**Issue by devhyunjae** [albertbellonch/piet#25]
Thanks for the awesome rubygem!

I have a little question. I want to optimize the image and also want to keep the original image.

and i coded like this,

```ruby
class ImageUploader < CarrierWave::Uploader::Base
  include Piet::CarrierWaveExtension
  process :optimize
  version :original
end
```

i was excepting two files

1. (optimized) uploaded_file.jpg
2. original_uploaded_file.jpg

but unfortunately, the original versioning is working with the image that already has been optimized :(

**Comment by indra-uolles** [comment]
maybe you should change the code like this?

```ruby
class ImageUploader < CarrierWave::Uploader::Base
  include Piet::CarrierWaveExtension

  version :original

  version :optimized do
    process :optimize
  end
end
```

**Comment by albertbellonch** [comment]
Hi @devhyunjae,

I think that what @indra-uolles pointed out is the best option. This way you have both the original one and the optimized one.

I understand the issue is closed then.

Thanks for using the gem! :D

Best,
