### ISSUE TITLE
Files don't get cleared after pngquant optimization

### ISSUE THREAD

**Issue by indra-uolles** [albertbellonch/piet#26]
Here's the code

```ruby
class PartnerImageUploader < CarrierWave::Uploader::Base
  include Sprockets::Rails::Helper
  include CarrierWave::MiniMagick
  include Piet::CarrierWaveExtension
  include CarrierWave::S3CacheUrl
  include CarrierWave::IdinaidiDefaults

  fog_public true

  version :full do
    process resize_to_fit: [180, 50]
    process :pngquant
  end

end
```

it works, I see in public/system/partner/image correct results, but I also see that in the app folder appear files with names like this: "\#\<File/0x007fe654ceb750\>" and they don't get cleared. What would you advise me to do?

**Comment by indra-uolles** [comment]
This issue can be closed, because it's a png_quantizator bug, not yours

**Comment by albertbellonch** [comment]
Hi @indra-uolles, sorry for the late response.

Even thought it's a `png_quantizator` bug, maybe we can do something about it? Is there an option for `png_quantizator` so it does not leave those files?

Best,

**Comment by indra-uolles** [comment]
Hi @albertbellonch,

They've fixed it: https://github.com/rogercampos/png_quantizator/issues/4

**Comment by albertbellonch** [comment]
Perfect then!
